const CLASS_DATA={Titan:{icon:"◆",color:"#ff9b57",tagline:"Stand where others fall.",description:"A fortified frontline Guardian built around resilience and strength.",role:"Frontline Defender",bonus:{resilience:10,strength:5},art:"assets/class/titan.svg"},Hunter:{icon:"◇",color:"#65dcff",tagline:"Move first. Strike clean.",description:"A swift and precise Guardian built around mobility and recovery.",role:"Recon Specialist",bonus:{mobility:10,recovery:5},art:"assets/class/hunter.svg"},Warlock:{icon:"✦",color:"#c39aff",tagline:"Knowledge becomes power.",description:"A disciplined scholar of impossible energies and hidden systems.",role:"Arcane Scholar",bonus:{intellect:10,discipline:5},art:"assets/class/warlock.svg"}};
const RACE_DATA={Human:{icon:"◉",color:"#74b8ff",tagline:"Adaptable. Determined. Unbroken.",description:"A survivor shaped by persistence and impossible odds.",art:"assets/race/human.svg"},Exo:{icon:"⬡",color:"#63ece7",tagline:"A human mind in a machine body.",description:"Precision, memory, and purpose forged in synthetic form.",art:"assets/race/exo.svg"},Awoken:{icon:"✧",color:"#c69cff",tagline:"Born between light and shadow.",description:"A cosmic lineage carrying mystery in every signal.",art:"assets/race/awoken.svg"}};
const ICONS={orbit:"◉",campaign:"⚔",map:"⌖",vault:"⬢",codex:"◫",console:"⚙",xp:"✦",glimmer:"◆",timer:"◷",rank:"✧",mission:"◇",lock:"⌁",Credits:"◆",Equipment:"⬡",Provisions:"◈",Vouchers:"▣",Miscellaneous:"✦"};
const SECTORS={Alpha:{icon:"◒"},Bravo:{icon:"▥"},Charlie:{icon:"⇄"},Delta:{icon:"◍"},Echo:{icon:"⌁"},Foxtrot:{icon:"⌨"},Golf:{icon:"▦"},Hotel:{icon:"◫"},Juliet:{icon:"♢"},Kilo:{icon:"▤"},Lima:{icon:"⌂"}};
const ITALIAN_PHRASES=[
["Come stai?","KOH-meh STAI","How are you?"],["Sto bene.","stoh BEH-neh","I am doing well."],["Grazie mille.","GRAHT-see-eh MEE-leh","Thank you very much."],["Sei bellissimo.","say behl-LEES-see-moh","You are very handsome."],["Sei fantastico.","say fan-TAH-stee-koh","You are fantastic."],["Ti amo.","tee AH-moh","I love you."],["Ti voglio bene.","tee VOH-lyoh BEH-neh","I care about you."],["Mi manchi.","mee MAHN-kee","I miss you."],["Mi fai sorridere.","mee fai sohr-REE-deh-reh","You make me smile."],["Sei il migliore.","say eel mee-LYOH-reh","You are the best."],["Ce la puoi fare!","cheh lah pwoy FAH-reh","You can do it!"],["Non arrenderti.","nohn ahr-rehn-DEHR-tee","Do not give up."],["Continua così!","kohn-TEE-noo-ah koh-ZEE","Keep it up!"],["Buona fortuna!","BWOH-nah fohr-TOO-nah","Good luck!"],["Hai vinto!","eye VEEN-toh","You won!"],["Bel colpo!","behl KOHL-poh","Nice shot!"],["Giochiamo!","joh-kee-AH-moh","Let us play!"],["Missione completata.","mee-see-OH-neh kohm-pleh-TAH-tah","Mission complete."],["La vittoria è tua.","lah veet-TOH-ree-ah eh TOO-ah","Victory is yours."],["Sono orgogliosa di te.","SOH-noh ohr-goh-LYOH-zah dee teh","I am proud of you."],["Sempre insieme.","SEM-preh een-SYEH-meh","Always together."],["Sei speciale.","say speh-CHAH-leh","You are special."],["Sei incredibile.","say een-kreh-DEE-bee-leh","You are incredible."],["Il mio campione.","eel MEE-oh kahm-pee-OH-neh","My champion."],["Oggi è il tuo giorno.","OHJ-jee eh eel TOO-oh JOHR-noh","Today is your day."],["Divertiti!","dee-VEHR-tee-tee","Have fun!"],["Che bello!","keh BEHL-loh","How wonderful!"],["Andiamo!","ahn-dee-AH-moh","Let us go!"],["Un altro livello!","oon AHL-troh lee-VEHL-loh","Another level!"],["Una squadra perfetta.","OO-nah SKWAH-drah pehr-FEHT-tah","A perfect team."],["Sono felice con te.","SOH-noh feh-LEE-cheh kohn teh","I am happy with you."],["Questa missione è per te.","KWEH-stah mee-see-OH-neh eh pehr teh","This mission is for you."],["Tanti auguri!","TAHN-tee ow-GOO-ree","Best wishes!"],["Buon compleanno!","bwohn kohm-pleh-AHN-noh","Happy birthday!"],["Amore mio.","ah-MOH-reh MEE-oh","My love."],["Sei la mia persona preferita.","say lah MEE-ah pehr-SOH-nah preh-feh-REE-tah","You are my favourite person."],["Con te è tutto più bello.","kohn teh eh TOO-toh pyoo BEHL-loh","Everything is better with you."],["Abbiamo una missione.","ahb-BYAH-moh OO-nah mee-see-OH-neh","We have a mission."],["Missione finale.","mee-see-OH-neh fee-NAH-leh","Final mission."],["Buon compleanno, amore mio.","bwohn kohm-pleh-AHN-noh ah-MOH-reh MEE-oh","Happy birthday, my love."]];
const CHALLENGES=[["What is Angel's favourite colour?",["Teal","Black","Seafoam Green","Blue"],2],
["48 ÷ (3 × 2) + 7 × 4 − 5 = ?",["29","31","33","37"],1],
["Which class receives a Resilience bonus?",["Titan","Hunter","Warlock"],0],
["Three caches contain 2,500 Glimmer each. Total?",["5,000","6,500","7,500","8,000"],2],
["What comes next: 2, 4, 8, 16…",["18","24","30","32"],3],
["What is 15% of 200?",["20","25","30","35"],2],
["Which origin has a machine body?",["Human","Exo","Awoken"],1],
["Unscramble the sector code: A H P L A",["Alpha","Delta","Hotel","Kilo"],0],
["I speak without a mouth and return what you say. What am I?",["A shadow","An echo","A clock","A map"],1],
["What is Angel's favourite ice cream flavour?",["French Vanilla","Yuzu","Coffee","Peanut Butter"],0],
["Which number does not belong: 3, 6, 9, 14, 12?",["3","6","14","12"],2],
["The more you take, the more you leave behind. What am I?",["Memories","Time","Footsteps","Photographs"],2]];
const REWARD_ORDER=[["Dungeon Crawler Carl","Rare","Equipment"],["Socks","Common","Equipment"],["Nintendo Gift Card","Legendary","Credits"],["Grooming Set","Uncommon","Miscellaneous"],["Barber Voucher","Exotic","Vouchers"],["Briefs","Common","Equipment"],["Amazon Gift Card","Rare","Credits"],["Favourite Chocolate","Uncommon","Provisions"],["Lottery Ticket","Exotic","Miscellaneous"],["Gum","Common","Provisions"],["Clothing Gift Card","Rare","Credits"],["Cap","Uncommon","Equipment"],["PlayStation Gift Card","Legendary","Credits"],["Belt","Uncommon","Equipment"],["Pottery Voucher","Rare","Vouchers"],["Ice Beer Cups","Uncommon","Miscellaneous"],["Socks 2","Common","Equipment"],["Crazy Bear Voucher","Rare","Vouchers"],["Nespresso Gift Card","Legendary","Credits"],["Sleeping Mask","Rare","Equipment"],["Nespresso Capsules","Uncommon","Provisions"],["Briefs 2","Common","Equipment"],["Steam Gift Card","Legendary","Credits"],["Picture Frame Set","Uncommon","Miscellaneous"],["GameStop Gift Card","Legendary","Credits"],["Cineplex Gift Card","Rare","Credits"],["Link Bracelet","Exotic","Equipment"],["Dinner Coupon","Exotic","Vouchers"],["Earrings","Exotic","Equipment"],["Jewelry Box","Legendary","Miscellaneous"],["Socks 3","Common","Equipment"],["Uber Eats Gift Card","Legendary","Credits"],["Ice Cream Date Voucher","Exotic","Vouchers"],["Briefs 3","Common","Equipment"],["Mini Golf Voucher","Rare","Vouchers"],["Instacart Gift Card","Rare","Credits"],["Massage Voucher","Exotic","Vouchers"],["Briefs IV","Rare","Miscellaneous"],["Gaming Mouse","Exotic","Miscellaneous"],["Final Birthday Gift","Exotic","Miscellaneous"]];
const SECTOR_PLACEMENTS={
  "Clothing Gift Card":{sector:"Alpha",hideSpot:"Guild Master side table"},
  "Jewelry Box":{sector:"Alpha",hideSpot:"Closet shelf beside plushies"},
  "Steam Gift Card":{sector:"Alpha",hideSpot:"Closet drawer 2"},
  "Amazon Gift Card":{sector:"Bravo",hideSpot:"Blanket shelf"},
  "Grooming Set":{sector:"Delta",hideSpot:"Under sink"},
  "Gum":{sector:"Kilo",hideSpot:"Somewhere inside"},
  "Pottery Voucher":{sector:"Charlie",hideSpot:"Glass cabinet"},
  "PlayStation Gift Card":{sector:"Echo",hideSpot:"TV stand"},
  "Cineplex Gift Card":{sector:"Echo",hideSpot:"Under coffee table"},
  "Earrings":{sector:"Foxtrot",hideSpot:"Futon"},
  "Nintendo Gift Card":{sector:"Foxtrot",hideSpot:"Drawers"},
  "Ice Beer Cups":{sector:"Golf",hideSpot:"Fridge"},
  "Nespresso Capsules":{sector:"Golf",hideSpot:"Oven"},
  "Favourite Chocolate":{sector:"Golf",hideSpot:"Pantry (last)"},
  "Uber Eats Gift Card":{sector:"Golf",hideSpot:"First aid"},
  "Gaming Mouse":{sector:"Juliet",hideSpot:"Drawer beside vacuum"},
  "Instacart Gift Card":{sector:"Hotel",hideSpot:"Jacket pocket"}
};
const RC_LABELS=[27,4,33,16,39,8,21,2,36,13,30,6,18,40,11,25,1,34,15,26,3,22,38,9,17,14,29,7,35,10,24,5,32,19,12,28,31,37,20,23];
const DEFAULT_CODES=["A140","B207","F333","D418","M505","B612","J727","K808","E919","L010","B111","K212","F313","D414","L515","G616","A717","J818","M919","I727","M828","B222","F323","E424","F737","H626","H020","M121","K929","K535","A131","M232","G333","B434","L030","G636","L525","L838","F939","A040"];
const LANGUAGE_TRIAL_IDS=Array.from({length:40},(_,i)=>i+1);
const TRIALS=REWARD_ORDER.map((r,index)=>{const id=index+1;const placement=SECTOR_PLACEMENTS[r[0]];let sourceType="depot";if(placement)sourceType="sector";if(r[0]==="Link Bracelet")sourceType="npc";if(r[0]==="Dinner Coupon"||r[0]==="Final Birthday Gift")sourceType="guild";return{id,reward:r[0],rarity:r[1],category:r[2],iconKey:r[2].toLowerCase(),sourceType,sector:placement?.sector||null,hideSpot:placement?.hideSpot||"",rcLabel:`RC${String(RC_LABELS[index]).padStart(2,"0")}`,phrase:ITALIAN_PHRASES[index],question:CHALLENGES[index%CHALLENGES.length],code:DEFAULT_CODES[index],xp:250+index*20,glimmer:r[2]==="Credits"?4000:0,stats:{mobility:index%5===0?3:0,resilience:index%6===0?3:0,recovery:index%7===0?3:0,discipline:index%8===0?3:0,strength:index%9===0?3:0,intellect:index%10===0?3:0}}});
